name: emoj
summary: emoj
version: '4.2.0'
description: |
  Find relevant emoji from text on the command-line.
base: core24
grade: stable
confinement: strict

apps:
  emoj:
    command: bin/emoj
    plugs: [network, x11]

parts:
  emoj:
    plugin: npm
    source: https://github.com/sindresorhus/emoj.git
    source-type: git
    source-tag: v4.2.0
    npm-include-node: true
    npm-node-version: "22.23.1"
    override-build: |
      craftctl default
      npm install --include=dev
      npm run build
      npm install -g --prefix "${CRAFT_PART_INSTALL}" --install-links "${PWD}"
    stage-packages:
      - xsel
