name: emoj
summary: emoj
version: 'latest'
description: |
  Find relevant emoji from text on the command-line.
base: core24
grade: stable
confinement: strict

apps:
  emoj:
    command: bin/npm run emoj
    plugs: [network, x11]

parts:
  emoj:
    plugin: npm
    source: https://github.com/sindresorhus/emoj.git
    source-type: git
    npm-include-node: true
    npm-node-version: "22.5.1"
    stage-packages:
      - xsel
